# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0006_auto_20190201_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
