# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0007_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
