# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0008_auto_20190205_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='slug',
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
