# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0009_auto_20190307_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=250)),
                ('email', models.EmailField(help_text='Required', max_length=250)),
                ('college', models.CharField(help_text='Required', max_length=250)),
                ('branch', models.CharField(help_text='Required', max_length=250)),
                ('Cource', models.CharField(help_text='Required', max_length=250)),
                ('Cource_fee', models.CharField(help_text='Required', max_length=250)),
                ('father_name', models.CharField(help_text='Required', max_length=250)),
                ('father_contact_no', models.CharField(help_text='Required', max_length=250)),
                ('Addmission_type', models.CharField(help_text='Required', max_length=250)),
                ('training_type', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField(help_text='Required')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
