# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0011_auto_20190308_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_student',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
