# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0012_add_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_student',
            name='Fee_paid',
            field=models.PositiveIntegerField(default=2, help_text='Required'),
            preserve_default=False,
        ),
    ]
